### ISSUE TITLE
Floating point error with high -log10 p-values?

### ISSUE THREAD

**Issue by VasLem** [statgen/locuszoom#276] opened 2022-06-25 15:06 UTC
Hi, I would like to mention that there is an issue with the numerical processing of the -log10 p-values,  the highest it gets is 31.38 . This causes a wrong report of the highest peaks to show up if higher peaks than this number exist.

**Comment by abought** [comment] 2022-06-27 17:53
Thanks for the report. Can you provide an example link where you are seeing this problem?

Also, is there a typo here (should this be referring to, eg, ~300)?

General notes:

* In theory LocusZoom can handle much more extreme pvalues than what you report ([example](https://my.locuszoom.org/gwas/325673/region/?chrom=16&start=56794528&end=57194528))
* In practice, how you load data to show in LocusZoom is very important. Many languages/ API servers run into numerical underflow for pvalues < ~10^-300 (some websites thus fill in fake values past that cutoff).
* Since JS is sensitive to underflow, we recommend storing -log10pvalue on ingest, rather than when sending it to the web browser- this handles a much wider range of values. Sending -log10p is how our my.locuszoom.org upload site shows extreme pvalues. (if underflow is detected, [we convert](https://github.com/abought/zorp/blob/develop/zorp/parser_utils.py#L23-L62) it to a number via a slower and more aggressive regex procedure)

We're used in many different websites- some via tabix, others via custom backends. It's hard to say exactly where the problem is without knowing which tool you use.... but I'd start by looking at the steps where data is read and sent to the browser.

If this is for a private site, I can be reached at `abought@umich.edu` for any direct links that you don't want to share on a public forum.

**Comment by sir4ur0n** [comment] 2022-07-04 12:38
My 2 cents: I agree with @abought : I also use LZ and I have values way over `31` (even over `300`) and it works just fine:
![image](https://user-images.githubusercontent.com/1204125/177156456-fcc656ea-1f77-47c1-9b35-6fca6eb320e1.png)

**Comment by abought** [comment] 2022-07-20 13:39
No reply from original author after ~3 weeks. I'm going to close this ticket to keep the backlog clear, but feel free to reopen if there's anything we can do to be of assistance.

**Closed as completed by abought** 2022-07-20 13:39 UTC
Labels: question
