### ISSUE TITLE
tooltip stays open if I ctrl-tab away

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/locuszoom#99] opened 2017-04-10 06:58 UTC
To reproduce:
1. Hover over a tooltip.
2. ctrl-tab away from the tab.
3. come back, and it stays open until I close it or re-mouse-out its point.

On <http://locuszoom.sph.umich.edu/locuszoomjs.php>, clicking a point usually makes it exclusive, but it fails to hide tooltips that were locked open by ctrl-tab.

**Comment by Frencil** [comment] 2017-06-09 04:35
Which browser are you using? I see part of this behavior in Chrome on Linux - ctrl+tab away and tooltips are still there when I come back - but as soon as my mouse moves anywhere over the entire page LocusZoom.js catches up. This makes this minor enough of an issue that it's not worth addressing... but you see tooltips persisting longer than that?

**Comment by pjvandehaar** [comment] 2017-06-09 05:49
On Chrome 58 and Safari 10 on macOS (behavior is identical):
- I hover a point, ctrl-tab away, move the mouse off where the point would be, ctrl-tab back, and now:
    - the tooltip stays open just like if I'd clicked the point. ie, when I hover other points, their tooltips are shown, and the point I ctrl-tabbed away from also remains open, but when I click another point the tooltip is closed as expected.
    - the point stays `highlighted` (dim halo, not the solid halo of `selected`), meaning that clicking another point doesn't clear its highlight (b/c that only clears `selected`).  Hovering on and off the point (ie, giving it a new `mouseout`) removes the halo as expected.

On Firefox 53 on macOS:
- the tooltip and selection have disappeared when I ctrl-tab back to LZ.  (ie, `mouseout` fires when I ctrl-tab away)

**Comment by pjvandehaar** [comment] 2017-06-09 06:17
It looks like it's a known bug that Chrome only fires `mouseout` on a repaint (generally triggered by a mouse move).  That would explain the Chrome58-on-Windows7 behavior, where `mouseout` fires after one frame.  Maybe on macOS they've optimized away even the return-to-tab repaint, and then somehow forget to ever fire `mouseout`?

**Comment by abought** [comment] 2019-09-23 17:51
Unable to reproduce, closing.

**Closed by abought** 2019-09-23 17:51 UTC
Labels: bug, priority low
